---
title: "Solo_Nest_Data_Analysis: Second Script Run"
author: "Aidan Cox"
date: "8/22/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Library List

```{r library}
library(data.table)
library(lubridate)
library(dplyr)
library(stringr)
library(ggplot2)
library(lme4)
library(aod)
library(scales)
```

## Combine data for testing H1
```{r H1}
solo_H1 <- solo_rs %>% dplyr::select(nestid, outcome_ka, colonial, position, coarse_nestpos, latitude, longitude)
ka_H1 <- ka_rs %>% dplyr::select(-c(result))
ka_H1 <- ka_H1 %>% rename(nestid = nest)
h1 <- rbind(solo_H1, ka_H1)
rm(solo_H1, ka_H1)
h1$colonial <- factor(h1$colonial)
```

## Colony Map
```{r colony map}
ggplot() +
  geom_point(data = filter(h1, colonial == 0), aes(x = longitude, y = latitude, fill = outcome_ka), shape = 24, color = "black", pch = 21) + # solo nester
  geom_point(data = filter(h1, colonial == 1), aes(x = longitude, y = latitude, color = outcome_ka)) + # colonial nester
  coord_quickmap() +
  theme_linedraw()
```

# Size analysis for known CR birds
```{r size-up}
chick_size <- fread("solonest_obs_data_entry_2122.csv")
chick_size$date <- as_date(chick_size$date, format = "%m/%d/%Y")
chick_size <- chick_size %>% group_by(nestid) %>% filter(date == max(date))
known_cr <- chick_size %>% filter(nestid == "solo3" | nestid == "solo5" | nestid == "solo6" | nestid == "solo8" | nestid == "solo14" | nestid == "solo17" | nestid == "solo20" | nestid == "solo22" | nestid == "solo23" | nestid == "solo26")
known_cr[11,] <- known_cr[7,] # duplicate solo6 since two chicks

ggplot(data = known_cr) +
  geom_bar(aes(x = ch1_size))
```

HYPOTHESIS 1: SOLO NEST SUCCESS LOWER THAN SUBCOLONY BUT SIMILAR TO EDGE

# initial exploration and viz.
```{r H1: explore}
# success by solo vs. colonial
ggplot(data = h1) +
  geom_bar(aes(x = colonial, fill = outcome_ka), position = "dodge")

# success by edge position
ggplot(data = h1) +
  geom_bar(aes(x = position, fill = outcome_ka), position = "dodge") # position as continuous

ggplot(data = h1) +
  geom_bar(aes(x = coarse_nestpos, fill = outcome_ka), position = "dodge") # position as factor

# location of diff. positions
ggplot(data = h1) +
  geom_point(aes(x = longitude, y = latitude, color = coarse_nestpos)) +
  coord_quickmap()
```
# H1: Modeling
```{r H1 Model}
h1$coarse_nestpos <- relevel(as.factor(h1$coarse_nestpos), ref = "2")
# full model 
h1.mod1 <- glm(outcome_ka ~ coarse_nestpos + latitude + longitude, data = h1, family = binomial)
summary(h1.mod1)

# individual variables
h1.mod.1 <- glm(outcome_ka ~ coarse_nestpos, data = h1, family = binomial)
h1.mod.2 <- glm(outcome_ka ~ latitude + longitude, data = h1, family = binomial)
summary(h1.mod.1) # this is the best performing model
summary(h1.mod.2)
```

Assess model fit:
```{r H1 Mod Fit}
# assess overall signif. of model using liklihood ratio test (chi-2 distrib.)
with(h1.mod.1, pchisq(null.deviance - deviance, df.null - df.residual, lower.tail = FALSE))

# find 95% CIs confidence intervals using standard errors of coefficients
exp(cbind(OR = coef(h1.mod.1), confint.default(h1.mod.1))) # note that all overlap 1

# calculate the overall significance of nest position
wald.test(b = coef(h1.mod1), Sigma = vcov(h1.mod1), Terms = 2:3)
# apply the same test to see if the difference between colonial edge nests and solo nests is signif. 
l <- cbind(0,1,-1)
wald.test(b = coef(h1.mod.1), Sigma = vcov(h1.mod.1), L = l)
```

HYPOTHESIS 2: SOLO NEST SUCCESS INFLUENCED BY HABITAT QUALITY
# initial exploration and visualization
```{r H@: vizualize}
# rocksize - rocksize 2 and 3 will be perfect predictors because there is only 1
ggplot(data = solo_rs) +
  geom_bar(aes(x = rock_yn, fill = outcome_ka), position = "dodge") # rock has little effect, slight success?

# pebbles
ggplot(data = solo_rs) +
  geom_bar(aes(x = pebble_distrib_nearby, fill = outcome_ka), position = "dodge") # more pebbs. assoc. w. fail

# neighbors?
ggplot(data = solo_rs) +
  geom_bar(aes(x = neighbs_yn, fill = outcome_ka), position = "dodge")

ggplot(data = solo_rs) +
  geom_boxplot(aes(x = prop_neighbs, color = outcome_ka), position = "dodge") # neighbors assoc. w. success

# dist_nearest_subcol_nest
ggplot(data = solo_rs) +
  geom_boxplot(aes(x = dist_nearest_subcol_nest_m, color = outcome_ka), position = "dodge") # little app. effect

# area
ggplot(data = solo_rs) +
  geom_bar(aes(x = area, fill = outcome_ka), position = "dodge") # mixed effects and small samples

```

build a model
```{r H2 Logit Model}
h2.mod1 <- glm(outcome_ka ~ rock_yn + pebble_distrib_nearby + prop_neighbs + dist_nearest_subcol_nest_m, data = solo_rs, family = binomial)
summary(h2.mod1)

# reduce the model to the two variables approaching signif
h2.mod2 <- glm(outcome_ka ~ pebble_distrib_nearby + prop_neighbs, data = solo_rs, family = binomial)
summary(h2.mod2)

# individual models
h2.mod.1 <- glm(outcome_ka ~ pebble_distrib_nearby, data = solo_rs, family = binomial)
h2.mod.2 <- glm(outcome_ka ~ prop_neighbs, data = solo_rs, family = binomial)
summary(h2.mod.1)
summary(h2.mod.2)
```

Assess model fit:
```{r H2 Mod Fit}
# assess the significance vs. null model using liklihood ratio test (chi-2 distrib.)
with(h2.mod2, pchisq(null.deviance - deviance, df.null - df.residual, lower.tail = FALSE)) # lowest p-value of any above model and nearly significant but not quite

logLik(h2.mod2)

# find the exponentiated coefficients (odds ratios) and  95% CIs confidence intervals using standard errors of coefficients
exp(cbind(OR = coef(h2.mod2), confint.default(h2.mod2))) # note that all overlap zero

# calculate the overall significance of nest position
wald.test(b = coef(h2.mod2), Sigma = vcov(h2.mod2), Terms = 2:3)
```
